version: '3'
services:
  db:
    image: postgres
    container_name: student-forum-db
    restart: always
  environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
  ports:
    - '5433:5432'
  volumes:
    - student_db:/var/lib/postgresql/data

volumes:
  db:
    driver: local