# Generated by Django 5.0 on 2024-02-01 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('External User', 'External User')], default='External User', max_length=15, validators=[django.core.validators.MinLengthValidator(2, message='Your role needs to consist of at least 2 letters!')]),
        ),
    ]
