# Generated by Django 5.0 on 2024-01-16 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_rename_topics_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(default="This subject doesn't have a description yet.", validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
