# Generated by Django 5.0 on 2024-01-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default='Someee', max_length=350, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
