# Generated by Django 5.0 on 2024-01-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_alter_comment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
    ]
