# Generated by Django 5.0 on 2024-01-28 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=350, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
