# Generated by Django 5.0 on 2024-02-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_alter_topic_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_add_topic', 'The user can add a new topic'),)},
        ),
    ]
