# Generated by Django 5.0 on 2024-02-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
