# Generated by Django 5.0 on 2024-02-16 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
